# Generated by Django 4.2.1 on 2023-06-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_items_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_img',
        ),
    ]
